export default {
  en: {
    response: {
      200: "OK",
      201: "Creation was successfully",
      202: "Reset message is sent!",
      203: "Update finished successfully",
      204: "Deletion completed successfully",
      205: "Logged in successfilly",
      206: "Logged out successfilly",
      207: "OTP has been sent to your email",
      400: "Missing required fields",
      401: "Unauthorized",
      402: "Passwords don't match",
      403: "Please enter valid phone number or email address!",
      404: "Not Found",
      405: "Account already exists",
      406: "Request has expired, Please try again!",
      407: "Invalid input", //for in valid ids
      408: "Address not found",
      409: "OTP doesn't match",
      410: "Your email is already verified",
      411: "Your phone number is already verified",
      412: "Your account is already verified",
      413: "Your account is not verified",
      414: "Your OTP has expired",
      415: "Please provide user id",
      416: "User not found",
      417: "Cart not found",
      418: "Invalid user id",
      419: "User is blocked",
      420: "User is unblocked",
      421: "User is already blocked",
      422: "User is already unblocked",
      423: "Stock type name is invalid",
      424: "Stock type is not found",
      425: "Invalid stock type id",
      426: "Invalid role id",
      427: "Stock item is not found",
      428: "Invalid stock item id",
      429: "Stock item is not found",
      430: "Invalid product category id",
      431: "Product category is not found",
      432: "Invalid product id",
      433: "Product is not found",
      434: "",
      435: "",
      436: "",
      500: "Internal Server Error, please try again!",
      501: "Not Implemented: it is under development",
    },
  },
};
