export default {
  en: {
    response: {
      200: "OK",
      201: "Creation was successfully",
      202: "Reset message is sent!",
      203: "Update finished successfully",
      204: "Deletion completed successfully",
      205: "Logged in successfilly",
      206: "Logged out successfilly",
      207: "OTP has been sent to your email",
      208: "Address was created successfully",
      209: "Your email is verified", //---
      210: "Your phone number is verified",
      211: "User is blocked",
      212: "User is unblocked",

      400: "Missing required fields",
      401: "Unauthorized",
      402: "Passwords don't match",
      403: "Please enter valid phone number or email address!",
      404: "Not Found",
      405: "Account already exists",
      406: "Request has expired, Please try again!",
      407: "Invalid input", //for in valid ids
      408: "Address not found",
      409: "OTP doesn't match",
      410: "Your email is already verified",
      411: "Your phone number is already verified",
      412: "Your phone number is verified",
      413: "Your email is verified",
      414: "Your OTP has expired",
      415: "Please provide user id",
      416: "User not found",
      417: "Cart not found",
      418: "Invalid user id",
      419: "User is blocked",
      420: "User is unblocked",
      421: "User is already blocked",
      422: "User is already unblocked",
      423: "Stock type name is invalid",
      424: "Stock type is not found",
      425: "Invalid stock type id",
      426: "Invalid role id",
      427: "Stock item is not found",
      428: "Invalid stock item id",
      429: "Stock item is not found",
      430: "Invalid product category id",
      431: "Product category is not found",
      432: "Invalid product id",
      433: "Product is not found",
      434: "Invalid address id",
      435: "Address is not found",
      436: "Role is not found",
      437: "Invalid product category id",
      438: "Stock item name is invalid",
      439: "Prices are type of number!",
      440: "Invalid product category name value!",
      441: "Invalid product name value!",
      442: "Invalid product description value!",
      443: "Invalid price value!",
      // 444: "Invalid cost value!",
      // 445: "Invalid additional price value!",
      446: "Invalid search input value!",
      447: "The password is incorrect!",
      448: "Invalid OTP id",
      449: "Authentication failed: No token provided",
      450: "Authentication failed: Invalid token",
      451: "Authentication failed: Token has expired",
      452: "Authentication failed: User not admin",
      500: "Internal Server Error, please try again!",
      501: "Not Implemented: it is under development",
    },
  },
  am: {
    response: {
      200: "እሺ",
      201: "ምስረታ ተሳክቷል",
      202: "ማደሻ መልእክት ተልኳል",
      203: "ማስተካከል ተሳክቷል",
      204: "ማጥፋት ተሳክቷል",
      205: "በተሳካ ሁኔታ ገብቷል",
      206: "በተሳካ ሁኔታ ወጥቷል",
      207: "OTP ወደ ኢሜልዎ ተልኳል",
      208: "አድራሻ በተሳካ ሁኔታ ተፈጥሯል",
      209: "መለያህ ተረጋግጧል",
      210: "ስልክ ቁጥርህ ተረጋግጧል",
      211: "ተጠቃሚ ታግዷል",
      212: "ተጠቃሚው እገዳው ተነስቷል",

      400: "አስፈላጊ መረጃ ይጎድላል",
      401: "ያልተፈቀደ",
      402: "የይለፍ ቃሎች አይዛመዱም",
      403: "እባክዎ የሚሰራ ስልክ ቁጥር ወይም ኢሜይል አድራሻ ያስገቡ!",
      404: "አልተገኘም",
      405: "መለያ አስቀድሞ አለ።",
      406: "ጥያቄው ጊዜው አልፎበታል፣ እባክዎ እንደገና ይሞክሩ!",
      407: "የገባው መረጃ ትክክል አይደለም",
      408: "አድራሻ አልተገኘም",
      409: "OTP አይዛመድም።",
      410: "ኢሜይልህ አስቀድሞ ተረጋግጧል",
      411: "ስልክ ቁጥርህ አስቀድሞ ተረጋግጧል",
      412: "ስልክ ቁጥርህ ተረጋግጧል",
      413: "ኢሜይልህ ተረጋግጧል",
      414: "የእርስዎ OTP ጊዜው አልፎበታል",
      415: "እባክዎ የተጠቃሚ መታወቂያ ያቅርቡ",
      416: "ተጠቃሚ አልተገኘም።",
      417: "ጋሪ አልተገኘም።",
      418: "የተሳሳተ የተጠቃሚ መታወቂያ",
      419: "ተጠቃሚ ታግዷል",
      420: "ተጠቃሚው እገዳው ተነስቷል",
      421: "ተጠቃሚ አስቀድሞ ታግዷል",
      422: "ተጠቃሚ አስቀድሞም እገዳው ተነስቷል",
      423: "የክምችቱ አይነት ስም ልክ ያልሆነ ነው።",
      424: "የክምችቱ አይነት አልተገኘም።",
      425: "ልክ ያልሆነ ክምችቱ አይነት መታወቂያ",
      426: "ልክ ያልሆነ የሚና መታወቂያ",
      427: "እቃው አልተገነም",
      428: "የእቃው መታወቂያ ልክ አይደለም",
      429: "የእቃው ስም ልክ አይደለም",
      430: "ልክ ያልሆነ የምርት ምድብ መታወቂያ",
      431: "የምርት ምድብ አልተገኘም።",
      432: "ልክ ያልሆነ የምርት መታወቂያ",
      433: "ምርቱ አልተገኘም።",
      434: "ልክ ያልሆነ የአድራሻ መታወቂያ",
      435: "አድራሻ አልተገኘም።",
      436: "ሚና አልተገኘም።",
      437: "ልክ ያልሆነ የምርት ምድብ መታወቂያ",
      438: "የእቃው ስም ልክ አይደለም",
      439: "ዋጋዎች የቁጥር አይነት ናቸው!",
      440: "ልክ ያልሆነ የምርት ምድብ ስም ዋጋ!",
      441: "ልክ ያልሆነ የምርት ስም ዋጋ!",
      442: "ልክ ያልሆነ የምርት መግለጫ ዋጋ!",
      443: "ልክ ያልሆነ የዋጋ ዋጋ!",
      // 444: "ልክ ያልሆነ የወጪ ዋጋ!",
      // 445: "ልክ ያልሆነ ተጨማሪ የዋጋ ዋጋ!",
      446: "ልክ ያልሆነ የፍለጋ ግቤት ዋጋ!",
      447: "የይለፍ ቃሉ የተሳሳተ ነው!",
      448: "ልክ ያልሆነ OTP መታወቂያ",
      449: "ማረጋገጥ አልተሳካም፡ ምንም ማስመሰያ አልቀረበም!",
      450: "ማረጋገጥ አልተሳካም፡ ልክ ያልሆነ ማስመሰያ!",
      451: "ማረጋገጥ አልተሳካም፡ ማስመሰያ ጊዜው አልፎበታል!",
      452: "ማረጋገጥ አልተሳካም፡ ተጠቃሚ አስተዳዳሪ አይደለም!",
      500: "የመረብ ብልሽት ተከስቷል፡ እባክዎን ትንሽ ቆይተው እንደገና ይሞክሩ!",
      501: "አልተተገበረም።: ልማት ላይ ነው።",
    },
  },
  or: {
    response: {
      200: "TOLE",
      433: "Omishni hin argamne",
    },
  },
};
