export default {
  en: {
    response: {
      200: "OK",
      201: "Creation was successfully",
      202: "Reset message is sent!",
      203: "Update finished successfully",
      204: "Deletion completed successfully",
      205: "Logged in successfilly",
      206: "Logged out successfilly",
      207: "OTP has been sent to your email",
      208: "Address was created successfully",
      400: "Missing required fields",
      401: "Unauthorized",
      402: "Passwords don't match",
      403: "Please enter valid phone number or email address!",
      404: "Not Found",
      405: "Account already exists",
      406: "Request has expired, Please try again!",
      407: "Invalid input", //for in valid ids
      408: "Address not found",
      409: "OTP doesn't match",
      410: "Your email is already verified",
      411: "Your phone number is already verified",
      412: "Your account is already verified",
      413: "Your account is not verified",
      414: "Your OTP has expired",
      415: "Please provide user id",
      416: "User not found",
      417: "Cart not found",
      418: "Invalid user id",
      419: "User is blocked",
      420: "User is unblocked",
      421: "User is already blocked",
      422: "User is already unblocked",
      423: "Stock type name is invalid",
      424: "Stock type is not found",
      425: "Invalid stock type id",
      426: "Invalid role id",
      427: "Stock item is not found",
      428: "Invalid stock item id",
      429: "Stock item is not found",
      430: "Invalid product category id",
      431: "Product category is not found",
      432: "Invalid product id",
      433: "Product is not found",
      434: "Invalid address id",
      435: "Address is not found",
      436: "Role is not found",
      437: "Invalid product category id",
      438: "Stock item name is invalid",
      439: "Prices are type of number!",
      440: "Invalid product category name value!",
      441: "Invalid product name value!",
      442: "Invalid product description value!",
      443: "Invalid price value!",
      444: "Invalid cost value!",
      445: "Invalid additional price value!",
      446: "Invalid search input value!",
      500: "Internal Server Error, please try again!",
      501: "Not Implemented: it is under development",
    },
  },
  am: {
    200: "እሺ",
    201: "ምስረታ ተሳክቷል",
    202: "ማደሻ መልእክት ተልኳል",
    203: "ማስተካከል ተሳክቷል",
    204: "ማጥፋት ተሳክቷል",
    205: "",
    206: "",
    207: "",
    208: "",
    400: "አስፈላጊ መረጃ ይጎድላል",
    401: "",
    402: "",
    403: "",
    404: "አልተገኘም",
    405: "",
    406: "",
    407: "የገባው መረጃ ትክክል አይደለም",
    408: "Address not found",
    409: "OTP doesn't match",
    410: "Your email is already verified",
    411: "Your phone number is already verified",
    412: "Your account is already verified",
    413: "Your account is not verified",
    414: "Your OTP has expired",
    415: "Please provide user id",
    416: "User not found",
    417: "Cart not found",
    418: "Invalid user id",
    419: "User is blocked",
    420: "User is unblocked",
    421: "User is already blocked",
    422: "User is already unblocked",
    423: "Stock type name is invalid",
    424: "Stock type is not found",
    425: "Invalid stock type id",
    426: "Invalid role id",
    427: "Stock item is not found",
    428: "Invalid stock item id",
    429: "Stock item is not found",
    430: "Invalid product category id",
    431: "Product category is not found",
    432: "Invalid product id",
    433: "Product is not found",
    434: "Invalid address id",
    435: "Address is not found",
    436: "Role is not found",
    500: "የመረብ ብልሽት ተከስቷል፡ እባክዎን ትንሽ ቆይተው እንደገና ይሞክሩ!",
    501: "Not Implemented: it is under development",
  },
  or: {
    433: "Product is not found",
  },
};
