export default {
  en: {
    response: {
      common: {
        200: "OK",
        201: "Creation completed successfully",
        202: "Update completed successfully",
        203: "Deletion completed successfully",

        400: "Missing required fields",
        401: "Unauthorized",
        404: "Not Found",
        405: "Invalid date provided",
        406: "Invalid input",
        407: "Prices are type of number and greater than zero! ",

        500: "Internal Server Error, please try again!",
        501: "Not Implemented: it is under development",
      },
      auth: {
        200: "Logged in successfully",
        201: "Logged out successfully",
        202: "OTP has been sent to your email",
        203: "Reset message is sent",
        204: "Your email is verified",
        205: "OTP has been sent to your phone number",
        206: "Your phone number is verified",

        400: "Account already exists",
        401: "Request has expired, Please try again!",
        403: "Your phone number is already verified",
        404: "Passwords don't match",
        405: "Please enter valid phone number or email address!",
        406: "OTP doesn't match",
        407: "Your OTP has expired",
        408: "The phone number is already in use",
        409: "Invalid OTP id",
        410: "The password is incorrect!",
        411: "Authentication failed: No token provided",
        412: "Authentication failed: Invalid token",
        413: "Authentication failed: Token has expired",
        414: "Authentication failed: User not admin",
        415: "Phone number is not registered in your account",
        416: "Email address is not registered in your account",
        417: "Message was not sent successfully",
        418: "The email is already in use",
        419: "Your email is already verified",
        420: "Please try another way to log in",
      },
      user: {
        201: "User is blocked",
        202: "User is unblocked",

        400: "Please provide user id",
        402: "Invalid user id",
        404: "User not found",
        405: "User is already blocked",
        406: "User is already unblocked",
      },
      cart: {
        404: "Cart not found",
      },
      product: {
        200: "You liked this product",
        201: "You unliked this product",

        401: "Invalid product name value!",
        402: "Invalid product id",
        403: "Invalid product description value!",
        404: "Product is not found",
        405: "Invalid tag value",
        406: "At least one tag is required",
        407: "Invalid price range values ",
        408: "Invalid stock variety list values",
      },
      address: {
        402: "Invalid address id",
        404: "Address is not found",
        405: "This address does not belong to this user", //----
      },
      stockType: {
        401: "Stock type name is invalid",
        402: "Invalid stock type id",
        404: "Stock type is not found",
      },
      role: {
        401: "Role name is type of string",
        402: "Invalid role id",
        404: "Role is not found",
        405: "The role already exists",
      },
      stockItem: {
        401: "Stock item name is invalid",
        402: "Invalid stock item id",
        404: "Stock item is not found",
        405: "stock item price is a number",
      },
      productCategory: {
        401: "Invalid product category name value!",
        402: "Invalid product category id",
        404: "Product category is not found",
      },
      order: {
        402: "Invalid order id",
        404: "Order not found",
        405: "This order does not belong to this user",
      },
      orderItem: {
        402: "Invalid order item id!",
        403: "Invalid order items value!",
        404: "Order item not found",
        405: "Order item can not be empty",
        406: "Quantity is a type of number",
        407: "Is checked is a type of boolean",
      },
      coupon: {
        401: "Invalid coupon name",
        402: "Invalid coupon code id!",
        404: "Coupon not found",
        405: "Coupon code is already exists",
      },
      orderStatus: {
        401: "Invalid order status name",
        404: "Order status not found",
      },
      review: {
        402: "Invalid review Id",
        403: "Rating is a type of number",
        404: "Review not found",
        405: "Review text is a value of type string",
        406: "A review has already been registered by this user",
        407: "Rating is between 1 and 5",
        408: "Specify the correct type of review",
      },
      discountType: {
        401: "Discount type name is invalid",
        402: "Invalid discount type id",
        404: "Discount type is not found",
        405: "Discount amount is a type of number and greater than zero",
        406: "Discount type already exists",
      },
      image: {
        401: "Image name is a type of string",
        402: "Invalid images id",
        403: "Image description is a type of string",
        404: "Images not found",
        406: "Primary is a type of number",
        407: "Invalid Primary image value",
        408: "Invalid image file",
        409: "Invalid images type value",
      },
      stockVariety: {
        402: "Invalid stock variety id",
        404: "Stock variety not found",
        407: "Number of available stock variety is type of number!",
        408: "Invalid stock variety value",
        409: "Stock variety for this product already exists",
        410: "Type is type of string, 'main' or 'sub'",
        411: "Invalid sub variants value",
        412: "Invalid image value, it's type of string",
      },
      stockVarietyType: {
        401: "Invalid stock variety type name",
        402: "Invalid stock variety type id",
        404: "stock variety type not found",
        406: "Stock variety type already exists",
      },
      dealType: {
        401: "Invalid deal type name",
        402: "Invalid deal type id",
        404: "Deal type not found",
        406: "Deal type already exists",
        407: "Invalid deal subtitle value",
      },
      deal: {
        401: "Invalid deal subtitle value",
        402: "Invalid deal id",
        404: "deal not found",
        406: "Invalid discounts list",
        407: "Discount list cannot be empty",
        408: "The discount already exists in another deal",
        409: "Invalid deal status value",
      },
      discount: {
        401: "Invalid discount name",
        402: "Invalid discount id",
        404: "Discount not found",
        405: "Discount amount is a type of number and greater than zero",
        406: "Invalid discount amount",
        407: "Invalid discount type",
        408: "Invalid lists of product",
        409: "Invalid discount status",
        410: "A product already exists in another discount",
      },
      productVariant: {
        402: "Invalid variant id",
        404: "Product variant not found",
        405: "Number of Available variants is type of number",
        406: "Index of image is type of number",
        407: "Stock varieties is a list",
        408: "Invalid stock varieties provided",
        409: "There is a missing stock variety type for this product",
        410: "This product does not accept product variants, Please update the product first!",
        411: "This variant already exists in this product",
        412: "Stock variety list cannot be empty",
        413: "Can't have multiple main stock variety",
      },
      orderStatus: {
        401: "Invalid order status name",
        402: "Invalid order status id",
        404: "Order status not found",
        406: "Order status already exists",
        407: "The Order status is in use, it cannot be deleted",
      },
    },
    message: {
      text: "Demakk: Your verification code is: ",
      title: "Demakk e-commerce site",
      greetings: "Hi",
      body: "Your Demakk password can be reset by clicking the button below. It expires in 10 minutes. If you did not request a new password, please ignore this email.",
      button: "Reset Password",
      regards: "Regards, ",
      name: "Demakk",
      company: "Demakk Printing Enterprise",
      location1: "Ethiopia, Addis Ababa,",
      location2: "Atena-tera, BY Bldg.",
      message: "Use this link to reset your password, ",
      content:
        "Thank you for choosing our Brand. Use the following OTP to complete your Sign Up procedures. OTP is valid for 5 minutes",
    },
  },
  am: {
    response: {
      common: {
        200: "እሺ",
        201: "ምስረታ ተሳክቷል",
        202: "ማስተካከል ተሳክቷል",
        203: "ማጥፋት ተሳክቷል",

        400: "አስፈላጊ መረጃ ይጎድላል",
        401: "ያልተፈቀደ",
        404: "አልተገኘም",
        405: "ልክ ያልሆነ ቀን ቀርቧል",
        406: "ልክ ያልሆነ ግቤት",
        407: "ዋጋዎች የቁጥር አይነት ናቸው!",

        500: "የመረብ ብልሽት ተከስቷል፡ እባክዎን ትንሽ ቆይተው እንደገና ይሞክሩ!",
        501: "አልተተገበረም።: ልማት ላይ ነው።",
      },
      auth: {
        200: "በተሳካ ሁኔታ ገብቷል",
        201: "በተሳካ ሁኔታ ወጥቷል",
        202: "OTP ወደ ኢሜልዎ ተልኳል",
        203: "ማደሻ መልእክት ተልኳል",
        204: "መለያህ ተረጋግጧል",
        205: "OTP ወደ ስልክ ቁጥርዎ ተልኳል",
        206: "ስልክ ቁጥርህ ተረጋግጧል",

        400: "መለያ አስቀድሞ አለ",
        401: "ጥያቄው ጊዜው አልፎበታል፣ እባክዎ እንደገና ይሞክሩ!",
        403: "ስልክ ቁጥርህ አስቀድሞ ተረጋግጧል",
        404: "የይለፍ ቃሎች አይዛመዱም",
        405: "እባክዎ የሚሰራ ስልክ ቁጥር ወይም ኢሜይል አድራሻ ያስገቡ!",
        406: "OTP አይዛመድም",
        407: "የእርስዎ OTP ጊዜው አልፎበታል",
        408: "ስልክ ቁጥሩ አስቀድሞ ጥቅም ላይ ውሏል",
        409: "ልክ ያልሆነ OTP መታወቂያ",
        410: "የይለፍ ቃሉ የተሳሳተ ነው!",
        411: "ማረጋገጥ አልተሳካም፡ ምንም ማስመሰያ አልቀረበም!",
        412: "ማረጋገጥ አልተሳካም፡ ልክ ያልሆነ ማስመሰያ!",
        413: "ማረጋገጥ አልተሳካም፡ ማስመሰያ ጊዜው አልፎበታል!",
        414: "ማረጋገጥ አልተሳካም፡ ተጠቃሚ አስተዳዳሪ አይደለም!",
        415: "ስልክ ቁጥር በመለያዎ ውስጥ አልተመዘገበም",
        416: "ኢሜል በመለያዎ ውስጥ አልተመዘገበም",
        417: "መልእክት በተሳካ ሁኔታ አልተላከም",
        418: "ኢሜይሉ አስቀድሞ ጥቅም ላይ ውሏል",
        419: "ኢሜይልህ አስቀድሞ ተረጋግጧል",
        420: "እባክዎ ለመግባት ሌላ መንገድ ይሞክሩ",
      },
      user: {
        201: "ተጠቃሚ ታግዷል",
        202: "ተጠቃሚው እገዳው ተነስቷል",

        400: "እባክዎ የተጠቃሚ መታወቂያ ያቅርቡ",
        402: "የተሳሳተ የተጠቃሚ መታወቂያ",
        404: "ተጠቃሚ አልተገኘም",
        405: "ተጠቃሚ አስቀድሞ ታግዷል",
        406: "ተጠቃሚ አስቀድሞም እገዳው ተነስቷ",
      },
      cart: {
        400: "ጋሪ አልተገኘም",
      },
      product: {
        200: "ይህን ምርት ወደውታል",
        201: "ይህን ምርት አልወደዱትም",

        400: "የእቃው ስም ልክ አይደለም",
        402: "ልክ ያልሆነ የምርት መታወቂያ",
        403: "ልክ ያልሆነ የምርት መግለጫ ዋጋ!",
        404: "ምርቱ አልተገኘም",
        405: "ልክ ያልሆነ የመለያ ዋጋ",
        406: "ቢያንስ አንድ መለያ ያስፈልጋል",
      },
      address: {
        402: "ልክ ያልሆነ የአድራሻ መታወቂያ",
        404: "አድራሻ አልተገኘም",
        405: "ይህ አድራሻ የዚህ ተጠቃሚ አይደለም", //----
      },
      stockType: {
        401: "የክምችቱ አይነት ስም ልክ ያልሆነ ነው",
        402: "ልክ ያልሆነ ክምችቱ አይነት መታወቂያ",
        404: "የክምችቱ አይነት አልተገኘም",
      },
      role: {
        401: "የሚና ስም የሕብረቁምፊ ዓይነት ነው",
        402: "ልክ ያልሆነ የሚና መታወቂያ",
        404: "ሚና አልተገኘም",
        405: "ሚናው አስቀድሞ አለ",
      },
      stockItem: {
        401: "የእቃው ስም ልክ አይደለም",
        402: "የእቃው መታወቂያ ልክ አይደለም",
        404: "እቃው አልተገነም",
      },
      productCategory: {
        401: "ልክ ያልሆነ የምርት ምድብ ስም ዋጋ!",
        402: "ልክ ያልሆነ የምርት ምድብ መታወቂያ",
        404: "የምርት ምድብ አልተገኘም",
      },
      order: {
        402: "የትዕዛዝ መታወቂያው ልክ ያልሆነ ነው",
        404: "ትዕዛዝ አልተገኘም",
        405: "ይህ ትዕዛዝ የዚህ ተጠቃሚ አይደለም",
      },
      orderItem: {
        401: "ልክ ያልሆነ የትዕዛዝ ዋጋ!",
        402: "ልክ ያልሆነ የትዕዛዝ ንጥል መታወቂያ ዋጋ!",
        404: "የትዕዛዝ ንጥል ነገር አልተገኘም",
        405: "የትዕዛዝ ንጥል ባዶ ሊሆን አይችልም",
        406: "ብዛት የቁጥር አይነት ነው",
      },
      coupon: {
        401: "ልክ ያልሆነ የኩፖን ስም",
        402: "ልክ ያልሆነ የኩፖን መታወቂያ!",
        404: "ኩፖን አልተገኘም",
      },
      orderStatus: {
        401: "ልክ ያልሆነ የትዕዛዝ ሁኔታ ስም",
        404: "የትዕዛዝ ሁኔታ አልተገኘም",
      },
      review: {
        403: "ደረጃ የቁጥር አይነት ነው",
        405: "የግምገማ ጽሑፍ የሕብረቁምፊ ዓይነት ዋጋ ነው",
        406: "ግምገማ አስቀድሞ በዚህ ተጠቃሚ ተመዝግቧል",
        407: "ደረጃ አሰጣጥ በ1 እና 5 መካከል ነው",
        408: "የግምገማውን አይነት ይግለጹ",
      },
      discountType: {
        401: "የቅናሽ አይነት ስም ልክ ያልሆነ ነው።",
        402: "ልክ ያልሆነ የቅናሽ አይነት መታወቂያ",
        404: "የቅናሽ አይነት አልተገኘም።",
        405: "የቅናሽ መጠን የቁጥር አይነት ነው",
        406: "የቅናሽ አይነት አስቀድሞ አለ።",
      },
      image: {
        401: "የምስል ስም የሕብረቁምፊ አይነት ነው",
        402: "ልክ ያልሆኑ ምስሎች መታወቂያ",
        403: "የምስል መግለጫ የሕብረቁምፊ አይነት ነው",
        406: "ቀዳሚ የቁጥር አይነት ነው",
        404: "ምስሎች አልተገኙም።",
        407: "ልክ ያልሆነ ቀዳሚ ምስል ዋጋ",
        408: "ልክ ያልሆነ የምስል ፋይል",
      },
      stockVariety: {},
      stockVarietyType: {},
    },
    message: {
      text: "ደማቅ፡ ይህ የእርሶ የማረጋገጫ ኮድ ነው: ",
      title: "ደማቅ ኢ-ንግድ ጣቢያ",
      greetings: "ሰላም",
      body: "የደማቅ ይለፍ ቃል ከዚህ በታች ያለውን ቁልፍ ጠቅ በማድረግ ዳግም ማስጀመር ይቻላል። በ 10 ደቂቃዎች ውስጥ ጊዜው ያበቃል. አዲስ የይለፍ ቃል ካልጠየቁ፣ እባክዎ ይህን ኢሜይል ችላ ይበሉ።",
      button: "የይለፍ ቃል ዳግም አስጀምር",
      regards: "ከሰላምታ ጋር, ",
      name: "ደማቅ",
      company: "ደማቅ ማተሚያ ድርጅት",
      location1: "ኢትዮጵያ, አዲስ አበባ",
      location2: "አጠና-ተራ, ቢዋይ ህንጻ",
      message: "የይለፍ ቃልዎን እንደገና ለማስጀመር ይህንን ሊንክ ይጠቀሙ, ",
      content:
        "የእኛን የምርት ስም ስለመረጡ እናመሰግናለን። የመመዝገቢያ ሂደቶችን ለማጠናቀቅ የሚከተለውን OTP ይጠቀሙ። OTP የሚሰራው ለ 5 ደቂቃዎች ነው።",
    },
  },
  or: {
    response: {
      common: {
        200: "TOLE",
        201: "Uumame milkaa'inaan xumurame",
        202: "Haaromsuu milkaa'inaan xumurame",
        203: "Haquu milkaa'inaan xumurame",

        400: "Kutaa barbaachisuutu dhumaa",
        401: "Eeyyamamee hin jiru",
        404: "Argamee hin jiru",
        405: "Guyyaa dogoggoraa laatame",
        406: "Galmee dogoggoraa",
        407: "Gatiiwwan lakkoofsaa fi kan irra guddaa!",

        500: "Dogoggora Server, mee irra deebii yaali!",
        501: "Hojii irra hin oolle: hojiirra oolaa jira",
      },
      auth: {
        200: "Milkaa'inaan seename",
        201: "Milkaa'inaan baane",
        202: "OTP ergameera email keetti",
        203: "Ergaa deebisuu ergameera",
        204: "Email kee mirkanaa'era",
        205: "OTP ergameera lakkoobsa bilbila keetti",
        206: "Lakkoobsi bilbila keeti mirkanaa'era",

        400: "Akaawuntiin dursee jira",
        401: "Gaaffiin yeroo darbee jira, mee irra deebii yaali!",
        403: "Lakkoobsi bilbila keet mirkanaa'ee jira",
        404: "Jecha darbii wal hin faalle",
        405: "Mee lakkoobsa bilbila sirrii yookan email galchi!",
        406: "OTP wal hin faalle",
        407: "OTP kee yeroo darbiteera",
        408: "Lakkoobsi bilbila dursee fayyadamaa jira",
        409: "OTP id dogoggora",
        410: "Jecha darbii sirrii miti!",
        411: "Mirkaneeffachuu dadhabe: Token hin kennamne",
        412: "Mirkaneeffachuu dadhabe: Token sirrii miti",
        413: "Mirkaneeffachuu dadhabe: Token yeroo darbiteera",
        414: "Mirkaneeffachuu dadhabe: Fayyadamni admin miti",
        415: "Lakkoobsi bilbila account kee keessatti hin galmaa'in",
        416: "Email account kee keessatti hin galmaa'in",
        417: "Ergaan milkaa'inaan hin ergamne",
        418: "Email dursee fayyadamaa jira",
        419: "Email kee dursee mirkanaa'ee jira",
        420: "Mee karaa biraa seenuuf yaali",
      },
      user: {
        201: "Fayyadamni uggurameera",
        202: "Uggurri fayyadamtootaa kaafameera",

        400: "Mee id fayyadamaa dhiheessi",
        402: "Id fayyadamaa dogoggora",
        404: "Fayyadamni hin argamne",
        405: "Fayyadamni dursee uggurameera",
        406: "Fayyadamni dursee uggurri kaafameera",
      },
      cart: {
        404: "Galaafni hin argamne",
      },
      product: {
        200: "Meeshaa kana jaalatte",
        201: "Meeshaa kana jaalala irraa kaaste",

        401: "Maqaa meeshaa dogoggora!",
        402: "Id meeshaa dogoggora",
        403: "Ibsa meeshaa dogoggora!",
        404: "Meeshaan hin argamne",
        405: "Maqaa maxxansa dogoggora",
        406: "Walakkaan tokko maxxansa barbaachisa",
        407: "Gatiiwwan daangeffamaa dogoggora",
        408: "Walitti hidhamiinsa gatiiwwan bakka bu'uura dogoggora",
      },
      address: {
        402: "Id bakka bu'uura dogoggora",
        404: "Bakka bu'uura hin argamne",
        405: "Bakka bu'uura kun fayyadama kanaaf hin ta'u",
      },
      stockType: {
        401: "Maqaa gosa ergamaa dogoggora",
        402: "Id gosa ergamaa dogoggora",
        404: "Gosa ergamaa hin argamne",
      },
      role: {
        401: "Maqaa qooda irra gosa kaawwa",
        402: "Id qooda dogoggora",
        404: "Qooda hin argamne",
        405: "Qoodni dursee jira",
      },
      stockItem: {
        401: "Maqaa ergamaa dogoggora",
        402: "Id ergamaa dogoggora",
        404: "Ergamaan hin argamne",
        405: "Gatiin ergamaa lakkoofsaa",
      },
      productCategory: {
        401: "Maqaa gosa meeshaa dogoggora!",
        402: "Id gosa meeshaa dogoggora",
        404: "Gosa meeshaa hin argamne",
      },
      order: {
        402: "Id ajajaa dogoggora",
        404: "Ajaji hin argamne",
        405: "Ajaji kun fayyadama kanaaf hin ta'u",
      },
      orderItem: {
        402: "Id kaawwachuu ajajaa dogoggora!",
        403: "Kaawwachuu ajajaa dogoggora!",
        404: "Kaawwachuu ajajaa hin argamne",
        405: "Kaawwachuun ajajaa hin ta'u",
        406: "Lakkofsaan sanduqaa",
        407: "Isaan ilaaluuf kanan ta'u booliyaa",
      },
      coupon: {
        401: "Maqaa kuufamaa dogoggora",
        402: "Id koodii kuufamaa dogoggora!",
        404: "Kuufama hin argamne",
        405: "Koodii kuufamaa dursee jira",
      },
      orderStatus: {
        401: "Maqaa haalata ajajaa dogoggora",
        404: "Haalata ajajaa hin argamne",
      },
      review: {
        402: "Id gorsaa dogoggora",
        403: "Sadarkaan lakkoofsaa",
        404: "Gorsi hin argamne",
        405: "Qabiyyee gorsaa sirrii miti",
        406: "Gorsi fayyadamaa kanaan dursee galmaa'era",
        407: "Sadarkaa 1-5 jidduu",
        408: "Gosa gorsa sirrii ibsi",
      },
      discountType: {
        401: "Maqaa gosa hir'ina dogoggora",
        402: "Id gosa hir'ina dogoggora",
        404: "Gosa hir'ina hin argamne",
        405: "Gatiin hir'ina lakkoofsaa fi kan irra guddaa",
        406: "Gosa hir'ina dursee jira",
      },
      image: {
        401: "Maqaa suuraa gosa",
        402: "Id suuraa dogoggora",
        403: "Ibsa suuraa gosa",
        404: "Suuraawwan hin argamne",
        406: "Gosa hangii",
        407: "Hangii suuraa sirrii miti",
        408: "Faayilii suuraa dogoggora",
        409: "Gosa suuraa sirrii miti",
      },
      stockVariety: {
        402: "Id bakka ergamaa dogoggora",
        404: "Bakka ergamaa hin argamne",
        407: "Baay'ina bakka ergamaa lakkoofsaa!",
        408: "Bakka ergamaa dogoggora",
        409: "Bakka ergamaa kanaf dursee jira",
        410: "Gosa gosa, 'bu'uura' ykn 'ilaalu",
        411: "Gosa bu'uura dogoggora",
        412: "Suuraa dogoggora, gosa kan string",
      },
      stockVarietyType: {
        401: "Maqaa gosa bakka ergamaa dogoggora",
        402: "Id gosa bakka ergamaa dogoggora",
        404: "Gosa bakka ergamaa hin argamne",
        406: "Gosa bakka ergamaa dursee jira",
      },
      dealType: {
        401: "Maqaa gosa waliigalaa dogoggora",
        402: "Id gosa waliigalaa dogoggora",
        404: "Gosa waliigalaa hin argamne",
        406: "Gosa waliigalaa dursee jira",
        407: "Ibsa gosa waliigalaa dogoggora",
      },
      deal: {
        401: "Ibsa gosa waliigalaa dogoggora",
        402: "Id waliigalaa dogoggora",
        404: "Waliigalaa hin argamne",
        406: "Walii galtee hir'ina dogoggora",
        407: "Walii galtee hir'ina yookaan tokko hin jirre",
        408: "Hir'inni biraan waliigalaa keessatti dursee jira",
        409: "Gosa waliigalaa dogoggora",
      },
      discount: {
        401: "Maqaa hir'ina dogoggora",
        402: "Id hir'ina dogoggora",
        404: "Hir'inni hin argamne",
        405: "Gatiin hir'ina lakkoofsaa fi kan irra guddaa",
        406: "Gatii hir'ina dogoggora",
        407: "Gosa hir'ina dogoggora",
        408: "Tarree meeshaa dogoggora",
        409: "Gosa hir'ina sirrii miti",
        410: "Meeshaan waliigalaa keessatti dursee jira",
      },
      productVariant: {
        402: "Id faayila dogoggora",
        404: "Faayilii meeshaa hin argamne",
        405: "Baay'ina bakka ergamaa lakkoofsaa",
        406: "Hangii suuraa lakkoofsaa",
        407: "Tarree bakka ergamaa",
        408: "Bakka ergamaa sirrii miti",
        409: "Bakka ergamaa kan dursee jira",
        410: "Meeshaan wal hin qaama, mee dursee meeshaa haaromsa!",
        411: "Faayilii kan dursee meeshaa keessatti jira",
        412: "Tarree bakka ergamaa yookaan hin jirre",
        413: "Bu'ura gosa kan lakkoofsaa hin jira",
      },
      orderStatus: {
        401: "Maqaa haalata ajajaa dogoggora",
        402: "Id haalata ajajaa dogoggora",
        404: "Haalata ajajaa hin argamne",
        406: "Haalata ajajaa dursee jira",
        407: "Haalata ajajaa hojiirra oolaa jira, haquu hin danda'amu",
      },
    },
    message: {
      text: "Demakk: Koodii mirkaneeffannaa kee: ",
      title: "Demakk e-commerce site",
      greetings: "Akkam",
      body: "Jecha darbii kee Demakk irraa deebisuuf, as qaree jalatti cuqaasi. Guutummaatti xumuramuuf daqiiqaa 10 fudhata. Yoo jechaa darbii haaraa hin gaafanne, ergaa kana hin ilaalin.",
      button: "Jecha Darbii Deebisi",
      regards: "Kabajaan,",
      name: "Demakk",
      company: "Demakk Printing Enterprise",
      location1: "Itoophiyaa, Finfinnee,",
      location2: "Atena-tera, BY Bldg.",
      message: "Jecha darbii kee deebisuuf, asitti qaree fayyadami,",
      content:
        "Al tajaajila keenyatti filuu kee galatoomaa. Galmeessuu kee xumuruu keessatti fayyadamuuf OTP kana fayyadami. OTP daqiiqaa 5f jiraata.",
    },
  },
};
