export default {
  en: {
    response: {
      200: "OK",
      201: "Creation was successfully",
      202: "Reset message is sent!",
      203: "Update finished successfully",
      204: "Deletion completed successfully",
      205: "Logged in successfilly",
      206: "Logged out successfilly",
      207: "OTP has been sent to your email",
      208: "Address was created successfully",
      209: "Your email is verified", //---
      210: "Your phone number is verified",
      211: "User is blocked",
      212: "User is unblocked",
      213: "OTP has been sent to your phone number",

      400: "Missing required fields",
      401: "Unauthorized",
      402: "Passwords don't match",
      403: "Please enter valid phone number or email address!",
      404: "Not Found",
      405: "Account already exists",
      406: "Request has expired, Please try again!",
      407: "Invalid input", //for in valid ids
      408: "Address not found",
      409: "OTP doesn't match",
      410: "Your email is already verified",
      411: "Your phone number is already verified",
      412: "Your phone number is verified",
      413: "Your email is verified",
      414: "Your OTP has expired",
      415: "Please provide user id",
      416: "User not found",
      417: "Cart not found",
      418: "Invalid user id",
      419: "User is blocked",
      420: "User is unblocked",
      421: "User is already blocked",
      422: "User is already unblocked",
      423: "Stock type name is invalid",
      424: "Stock type is not found",
      425: "Invalid stock type id",
      426: "Invalid role id",
      427: "Stock item is not found",
      428: "Invalid stock item id",
      429: "Stock item is not found",
      430: "Invalid product category id",
      431: "Product category is not found",
      432: "Invalid product id",
      433: "Product is not found",
      434: "Invalid address id",
      435: "Address is not found",
      436: "Role is not found",
      437: "Invalid product category id",
      438: "Stock item name is invalid",
      439: "Prices are type of number!",
      440: "Invalid product category name value!",
      441: "Invalid product name value!",
      442: "Invalid product description value!",
      443: "Price is a type of number!",
      // 444: "Invalid cost value!",
      // 445: "Invalid additional price value!",
      446: "Invalid search input value!",
      447: "The password is incorrect!",
      448: "Invalid OTP id",
      449: "Authentication failed: No token provided",
      450: "Authentication failed: Invalid token",
      451: "Authentication failed: Token has expired",
      452: "Authentication failed: User not admin",
      453: "Phone number is not registered in your account",
      454: "Email address is not registered in your account",
      455: "Language is type of two character string",
      456: "Language is not found",
      457: "Message was not sent successfully",
      458: "The email is already in use",
      459: "The password is already in use",
      460: "Invalid tag value",
      461: "The role already exists",
      462: "Role name is type of string",
      463: "This address does not belong to this user", //----
      464: "Invalid order id",
      465: "Quantity is a type of number",
      466: "Invalid coupon code id!",
      467: "Order item can not be empty",
      468: "Ordet items is a type of Array",
      469: "Invalid date provided",
      470: "Invalid order status name",
      471: "Order not found",
      472: "This order does not belong to this user ",
      473: "Order status not found",
      500: "Internal Server Error, please try again!",
      501: "Not Implemented: it is under development",
    },
    message: {
      text: "Demakk: Your verification code is: ",
      title: "Demakk ecommerce site",
      greetings: "Hi",
      body: "Your Demmakk password can be reset by clicking the button below. It expires in 10 minutes. If you did not request a new password, please ignore this email.",
      button: "Reset Password",
      regards: "Regards, ",
      name: "Demakk",
      company: "Demakk Printing Enterprise",
      location1: "Ethiopia, Addis Ababa,",
      location2: "Atena-tera, BY Bldg.",
      message: "Use this link to reset your password, ",
    },
  },
  am: {
    response: {
      200: "እሺ",
      201: "ምስረታ ተሳክቷል",
      202: "ማደሻ መልእክት ተልኳል",
      203: "ማስተካከል ተሳክቷል",
      204: "ማጥፋት ተሳክቷል",
      205: "በተሳካ ሁኔታ ገብቷል",
      206: "በተሳካ ሁኔታ ወጥቷል",
      207: "OTP ወደ ኢሜልዎ ተልኳል",
      208: "አድራሻ በተሳካ ሁኔታ ተፈጥሯል",
      209: "መለያህ ተረጋግጧል",
      210: "ስልክ ቁጥርህ ተረጋግጧል",
      211: "ተጠቃሚ ታግዷል",
      212: "ተጠቃሚው እገዳው ተነስቷል",
      213: "OTP ወደ ስልክ ቁጥርዎ ተልኳል",

      400: "አስፈላጊ መረጃ ይጎድላል",
      401: "ያልተፈቀደ",
      402: "የይለፍ ቃሎች አይዛመዱም",
      403: "እባክዎ የሚሰራ ስልክ ቁጥር ወይም ኢሜይል አድራሻ ያስገቡ!",
      404: "አልተገኘም",
      405: "መለያ አስቀድሞ አለ።",
      406: "ጥያቄው ጊዜው አልፎበታል፣ እባክዎ እንደገና ይሞክሩ!",
      407: "የገባው መረጃ ትክክል አይደለም",
      408: "አድራሻ አልተገኘም",
      409: "OTP አይዛመድም።",
      410: "ኢሜይልህ አስቀድሞ ተረጋግጧል",
      411: "ስልክ ቁጥርህ አስቀድሞ ተረጋግጧል",
      412: "ስልክ ቁጥርህ ተረጋግጧል",
      413: "ኢሜይልህ ተረጋግጧል",
      414: "የእርስዎ OTP ጊዜው አልፎበታል",
      415: "እባክዎ የተጠቃሚ መታወቂያ ያቅርቡ",
      416: "ተጠቃሚ አልተገኘም።",
      417: "ጋሪ አልተገኘም።",
      418: "የተሳሳተ የተጠቃሚ መታወቂያ",
      419: "ተጠቃሚ ታግዷል",
      420: "ተጠቃሚው እገዳው ተነስቷል",
      421: "ተጠቃሚ አስቀድሞ ታግዷል",
      422: "ተጠቃሚ አስቀድሞም እገዳው ተነስቷል",
      423: "የክምችቱ አይነት ስም ልክ ያልሆነ ነው።",
      424: "የክምችቱ አይነት አልተገኘም።",
      425: "ልክ ያልሆነ ክምችቱ አይነት መታወቂያ",
      426: "ልክ ያልሆነ የሚና መታወቂያ",
      427: "እቃው አልተገነም",
      428: "የእቃው መታወቂያ ልክ አይደለም",
      429: "የእቃው ስም ልክ አይደለም",
      430: "ልክ ያልሆነ የምርት ምድብ መታወቂያ",
      431: "የምርት ምድብ አልተገኘም።",
      432: "ልክ ያልሆነ የምርት መታወቂያ",
      433: "ምርቱ አልተገኘም።",
      434: "ልክ ያልሆነ የአድራሻ መታወቂያ",
      435: "አድራሻ አልተገኘም።",
      436: "ሚና አልተገኘም።",
      437: "ልክ ያልሆነ የምርት ምድብ መታወቂያ",
      438: "የእቃው ስም ልክ አይደለም",
      439: "ዋጋዎች የቁጥር አይነት ናቸው!",
      440: "ልክ ያልሆነ የምርት ምድብ ስም ዋጋ!",
      441: "ልክ ያልሆነ የምርት ስም ዋጋ!",
      442: "ልክ ያልሆነ የምርት መግለጫ ዋጋ!",
      443: "ልክ ያልሆነ የዋጋ ዋጋ!",
      // 444: "ልክ ያልሆነ የወጪ ዋጋ!",
      // 445: "ልክ ያልሆነ ተጨማሪ የዋጋ ዋጋ!",
      446: "ልክ ያልሆነ የፍለጋ ግቤት ዋጋ!",
      447: "የይለፍ ቃሉ የተሳሳተ ነው!",
      448: "ልክ ያልሆነ OTP መታወቂያ",
      449: "ማረጋገጥ አልተሳካም፡ ምንም ማስመሰያ አልቀረበም!",
      450: "ማረጋገጥ አልተሳካም፡ ልክ ያልሆነ ማስመሰያ!",
      451: "ማረጋገጥ አልተሳካም፡ ማስመሰያ ጊዜው አልፎበታል!",
      452: "ማረጋገጥ አልተሳካም፡ ተጠቃሚ አስተዳዳሪ አይደለም!",
      453: "ስልክ ቁጥር በመለያዎ ውስጥ አልተመዘገበም",
      454: "ኢሜል በመለያዎ ውስጥ አልተመዘገበም",
      455: "ቋንቋ የሁለት ፊደል ሕብረቁምፊ ዓይነት ነው",
      456: "ቋንቋ አልተገኘም",
      457: "መልእክት በተሳካ ሁኔታ አልተላከም",
      458: "ኢሜይሉ አስቀድሞ ጥቅም ላይ ውሏል",
      459: "ስልክ ቁጥሩ አስቀድሞ ጥቅም ላይ ውሏል",
      460: "ልክ ያልሆነ የመለያ ዋጋ",
      461: "ሚናው አስቀድሞ አለ",
      462: "የሚና ስም የሕብረቁምፊ ዓይነት ነው",
      463: "ይህ አድራሻ የዚህ ተጠቃሚ አይደለም",
      464: "የትዕዛዝ መታወቂያው ልክ ያልሆነ ነው",
      465: "ብዛት የቁጥር አይነት ነው",
      466: "ልክ ያልሆነ የኩፖን ኮድ መታወቂያ",
      467: "የትዕዛዝ ንጥል ባዶ ሊሆን አይችልም",
      468: "የትእዛዝ እቃዎች የድርድር አይነት ነው",
      469: "ልክ ያልሆነ ቀን ቀርቧል",
      470: "ልክ ያልሆነ የትዕዛዝ ሁኔታ ስም",
      471: "ትዕዛዝ አልተገኘም",
      472: "ይህ ትዕዛዝ የዚህ ተጠቃሚ አይደለም",
      473: "የትዕዛዝ ሁኔታ አልተገኘም",
      500: "የመረብ ብልሽት ተከስቷል፡ እባክዎን ትንሽ ቆይተው እንደገና ይሞክሩ!",
      501: "አልተተገበረም።: ልማት ላይ ነው።",
    },
    message: {
      text: "ደማቅ፡ ይህ የእርሶ የማረጋገጫ ኮድ ነው: ",
      title: "ደማቅ ኢ-ንግድ ጣቢያ",
      greetings: "ሰላም",
      body: "የደማቅ ይለፍ ቃል ከዚህ በታች ያለውን ቁልፍ ጠቅ በማድረግ ዳግም ማስጀመር ይቻላል። በ 10 ደቂቃዎች ውስጥ ጊዜው ያበቃል. አዲስ የይለፍ ቃል ካልጠየቁ፣ እባክዎ ይህን ኢሜይል ችላ ይበሉ።",
      button: "የይለፍ ቃል ዳግም አስጀምር",
      regards: "ከሰላምታ ጋር, ",
      name: "ደማቅ",
      company: "ደማቅ ማተሚያ ድርጅት",
      location1: "ኢትዮጵያ, አዲስ አበባ",
      location2: "አጠና-ተራ, ቢዋይ ህንጻ",
      message: "የይለፍ ቃልዎን እንደገና ለማስጀመር ይህንን ሊንክ ይጠቀሙ, ",
    },
  },
  or: {
    response: {
      200: "TOLE",
      433: "Omishni hin argamne",
    },
  },
};
